# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Releases/Contracts.Core/0.9.0

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Contracts/Contracts.Core/Core.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'Contracts/nuget.config'

- task: MSBuild@1
  inputs:
    solution: 'Contracts/Contracts.Core/Core.csproj'
    msbuildArchitecture: 'x64'
    clean: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'Contracts/Contracts.Core/Core.csproj'
    includesymbols: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '9'
    patchVersion: '0'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '38bc0da1-3319-433c-a904-026e89025e23/ee6b9c5d-1dfb-404c-ad78-604066a68c11'